"""
core/database.py — Persistent Intelligence Logging System (SQLite).

Captures every AI assessment generated by the app and stores user feedback
(Like / Dislike + free-text comments) so model accuracy can be audited over
time.  The database file (intelligence.db) lives in the project root.

Public API
----------
init_intelligence_db()        — create tables if they don't exist.
log_ai_assessment(...)        — insert a new assessment row, return row id.
update_feedback(row_id, ...)  — attach user feedback to an existing row.
fetch_disliked_assessments()  — return all rows marked "Dislike".
fetch_all_assessments(limit)  — return most-recent rows (any feedback state).
"""

from __future__ import annotations

import json
import os
import sqlite3
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

# ── Database location ─────────────────────────────────────────────────────────
_DB_DIR = Path(__file__).resolve().parent.parent          # project root
_DB_PATH = _DB_DIR / "intelligence.db"


# ══════════════════════════════════════════════════════════════════════════════
# INITIALISATION
# ══════════════════════════════════════════════════════════════════════════════

def init_intelligence_db() -> None:
    """Create the intelligence database and *feedback_logs* table if needed."""
    con = sqlite3.connect(str(_DB_PATH))
    try:
        con.execute("""
            CREATE TABLE IF NOT EXISTS feedback_logs (
                id              INTEGER PRIMARY KEY AUTOINCREMENT,
                entity_name     TEXT    NOT NULL,
                entity_type     TEXT    NOT NULL DEFAULT 'charity',
                assessment_type TEXT    NOT NULL DEFAULT 'full_report',
                ai_output       TEXT    NOT NULL,
                risk_level      TEXT,
                model_used      TEXT,
                user_feedback   TEXT,
                user_comments   TEXT,
                timestamp       TEXT    NOT NULL,
                feedback_ts     TEXT
            );
        """)
        con.commit()
    finally:
        con.close()


# Auto-initialise on first import so write helpers don't fail when the
# DB file is fresh. Cheap (CREATE TABLE IF NOT EXISTS) and idempotent.
init_intelligence_db()


# ══════════════════════════════════════════════════════════════════════════════
# WRITE HELPERS
# ══════════════════════════════════════════════════════════════════════════════

def log_ai_assessment(
    entity_name: str,
    ai_json_output: dict | str,
    *,
    entity_type: str = "charity",
    assessment_type: str = "full_report",
    risk_level: str = "",
    model_used: str = "",
) -> int:
    """Insert a new AI assessment row.  Returns the row *id*."""
    if isinstance(ai_json_output, dict):
        ai_text = json.dumps(ai_json_output, default=str)
    else:
        ai_text = str(ai_json_output)

    now = datetime.now(timezone.utc).isoformat()
    con = sqlite3.connect(str(_DB_PATH))
    try:
        cur = con.execute(
            """
            INSERT INTO feedback_logs
                (entity_name, entity_type, assessment_type,
                 ai_output, risk_level, model_used, timestamp)
            VALUES (?, ?, ?, ?, ?, ?, ?)
            """,
            (entity_name, entity_type, assessment_type,
             ai_text, risk_level, model_used, now),
        )
        con.commit()
        return cur.lastrowid  # type: ignore[return-value]
    finally:
        con.close()


def update_feedback(
    row_id: int,
    feedback: str,
    comments: str = "",
) -> None:
    """Attach user feedback ('Like' / 'Dislike') and optional comments."""
    now = datetime.now(timezone.utc).isoformat()
    con = sqlite3.connect(str(_DB_PATH))
    try:
        con.execute(
            """
            UPDATE feedback_logs
               SET user_feedback = ?,
                   user_comments = ?,
                   feedback_ts   = ?
             WHERE id = ?
            """,
            (feedback, comments, now, row_id),
        )
        con.commit()
    finally:
        con.close()


# ══════════════════════════════════════════════════════════════════════════════
# READ HELPERS
# ══════════════════════════════════════════════════════════════════════════════

def fetch_disliked_assessments(limit: int = 200) -> list[dict[str, Any]]:
    """Return rows where user_feedback == 'Dislike', newest first."""
    return _query(
        """
        SELECT id, entity_name, entity_type, assessment_type,
               ai_output, risk_level, model_used,
               user_feedback, user_comments, timestamp, feedback_ts
          FROM feedback_logs
         WHERE user_feedback = 'Dislike'
         ORDER BY feedback_ts DESC
         LIMIT ?
        """,
        (limit,),
    )


def fetch_all_assessments(limit: int = 100) -> list[dict[str, Any]]:
    """Return the most recent assessment rows regardless of feedback."""
    return _query(
        """
        SELECT id, entity_name, entity_type, assessment_type,
               ai_output, risk_level, model_used,
               user_feedback, user_comments, timestamp, feedback_ts
          FROM feedback_logs
         ORDER BY id DESC
         LIMIT ?
        """,
        (limit,),
    )


# ── Internal query helper ────────────────────────────────────────────────────

def _query(sql: str, params: tuple = ()) -> list[dict[str, Any]]:
    con = sqlite3.connect(str(_DB_PATH))
    con.row_factory = sqlite3.Row
    try:
        rows = con.execute(sql, params).fetchall()
        return [dict(r) for r in rows]
    finally:
        con.close()
